/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package greeter;

import greeter.lib.Library;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(Library.greeting("Hello Jet"));
    }
}
