/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package greeter.lib

import groovy.transform.CompileStatic

@CompileStatic
class Library {
    static String greeting(final String name) {
    	"Hello,${name.capitalize()}"
    }
}
